server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dipesh-pardeshi/config-repo
          search-paths: userservice, itemservice
        encrypt:
          enabled: false